#### Reddxchange, part of Reddconomy

# Choose between "enabled", "link", "disabled"
EnableQR: "enabled"

# Choose a coin (example: reddcoin | example2: dogecoin)
coin: "dogecoin"

# Set the api url without slash at the end
reddconomy_api_url: "http://reddconomy.frk.wf:8099"