name: ExchangeCoin
main: net.blockstreet.coin.Exchange
version: 0.0.1
author: Soxasora
commands:
  deposit:
    description: Show deposit address.
    usage: /deposit
    permission: ExchangeCoin.deposit
    permission-message: You don't have <permission>